_BASE_: Base.yaml
MODEL:
  META_ARCHITECTURE: "PlaneTR_NopeSAC"
  MASK_ON: True
  DEPTH_ON: False
  CAMERA_ON: False
  EMBEDDING_ON: False
  HUNGARIAN_MATCHER_ON: True
  LOSS_DETECTION_ON: True
  LOSS_CAMERA_ON: False
  LOSS_EMB_ON: False
  SEM_SEG_HEAD:
    NAME: "PlaneTRHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "GN"
    NUM_CLASSES: 1
    PARAM_ON: True
    CENTER_ON: True
    DEEP_SUPERVISION: True
    LOSS_WEIGHT: 1.0
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    PARAM_WEIGHT_L1: 0.25
    PARAM_HM_WEIGHT_L1: 0.25
    PARAM_WEIGHT_COS: 1.0
    PARAM_WEIGHT_Q: 1.0
    PARAM_WEIGHT_CENTER_INS: 0.5
    PARAM_WEIGHT_ANGLE: 0.0028
    PARAM_WEIGHT_OFFSET: 0.01
SOLVER:
  IMS_PER_BATCH: 16
  OPTIMIZER: "ADAMW"
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 2000
  STEPS: (10000,)
  BASE_LR: 0.0001
  GAMMA: 1.0
  BACKBONE_MULTIPLIER: 1.0
  SEM_SEG_HEAD_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: False

DATASETS:
  TRAIN: ("mp3d_train",)
  TEST: ("mp3d_val",)

TEST:
  EVAL_PERIOD: 2000
  EVAL_FULL_SCENE: False

DATALOADER:
  NUM_WORKERS: 16

OUTPUT_DIR: "ckpts_mp3d/step1/"

