_BASE_: Base.yaml
MODEL:
  META_ARCHITECTURE: "PlaneTR_NopeSAC"
  MASK_ON: True
  CAMERA_ON: True
  EMBEDDING_ON: True
  HUNGARIAN_MATCHER_ON: True
  LOSS_DETECTION_ON: True
  LOSS_CAMERA_ON: True
  LOSS_EMB_ON: True
  SEM_SEG_HEAD:
    NAME: "PlaneTRHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "GN"
    NUM_CLASSES: 1
    PARAM_ON: True
    CENTER_ON: True
    LOSS_WEIGHT: 1.0
    PARAM_WEIGHT_L1: 0.25
    PARAM_HM_WEIGHT_L1: 0.25
    PARAM_WEIGHT_COS: 1.0
  CAMERA_HEAD:
    REFINE_ON: True
    CAM_REC_ON: True
    RAND_ON: True
    PLANE_CAM_WEIGHT: 0.5
    PLANE_CAM_WEIGHT_PREDPLANE: 0.1
    NAME: "PlaneCameraHead"
    WARP_PLANE_IN_CAM_REF_ON: True
  WEIGHTS: "ckpts_mp3d/step2/model_final.pth"
SOLVER:
  IMS_PER_BATCH: 16
  OPTIMIZER: "ADAMW"
  MAX_ITER: 14000
  CHECKPOINT_PERIOD: 2000
  STEPS: (6000,)
  BASE_LR: 0.0001
  GAMMA: 0.1
  BACKBONE_MULTIPLIER: 1.0
  PLANE_MATCHER_HEAD_MULTIPLIER: 1.0
  SEM_SEG_HEAD_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: false

DATASETS:
  TRAIN: ("mp3d_train",)
  TEST: ("mp3d_val",)

TEST:
  EVAL_PERIOD: 2000
  EVAL_FULL_SCENE: False
  MATCHING_SCORE_THRESHOLD: 0.2

DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: "ckpts_mp3d/step3/"
FIX_SEED: True